services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
    
  #Redis Database
  redis:
    image: docker.io/redis
    command: ["redis-server", "--protected-mode", "no"]

  #Express API Server
  api:
    build:  ./server
    image: docker.io/ipsita10/complex-api
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432

  #Worker service
  worker:
    build:  ./worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  # React client
  client:
    build: ./client
    image:  docker.io/ipsita10/complex-client

  nginx:
    depends_on:
        - api
        - client
    restart: always
    build:  ./nginx
    ports:
        - '8082:80'